# ============================================
# Inventory: DOCKER Environment (Local Lab)
# Usage: ansible-playbook -i inventories/docker/hosts.ini playbooks/site.yml
# ============================================

[webservers]
web01 ansible_host=web01

[dbservers]
db01 ansible_host=db01

[all:vars]
ansible_user=t1kayyyy
ansible_python_interpreter=/usr/bin/python3
env=docker
